# Generated by Django 6.1 on 2026-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['reset_at'], name='accounts_ra_reset_a_5396d6_idx')],
            },
        ),
    ]
