# Generated by Django 6.1 on 2026-09-14 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('validation_error', models.TextField(blank=True)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistic_submissions', to='licensing.installation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaderboardAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('net_words', 'Net words'), ('words_added', 'Words added'), ('words_removed', 'Words removed'), ('active_seconds', 'Active time'), ('focus_seconds', 'Focus time'), ('session_count', 'Sessions')], max_length=40)),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('all_time', 'All time')], max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('value', models.BigIntegerField(default=0)),
                ('source', models.CharField(choices=[('sync', 'Client sync'), ('admin', 'Administrative'), ('import', 'Import')], default='sync', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-value', 'id'),
                'indexes': [models.Index(fields=['metric', 'period', 'period_start', '-value'], name='leaderboard_metric_c1740b_idx'), models.Index(fields=['user', 'metric', 'period'], name='leaderboard_user_id_b4beaa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'metric', 'period', 'period_start'), name='unique_aggregate_slot')],
            },
        ),
    ]
